add 2.0.8 files

diff --git a/system/xbin/pdsshd-toolkit b/system/xbin/pdsshd-toolkit
--- a/system/xbin/pdsshd-toolkit
+++ b/system/xbin/pdsshd-toolkit
@@ -1,20 +1,31 @@
 #!/system/xbin/bash
 
 #Written by:
-#Geofferey@XDA ©2015
+#Geofferey@XDA ©2016
 
-CONFIG=/system/etc/sshd.conf
+CONF=/system/etc/pdsshd.conf
 
-. /system/etc/sshd.conf
+. "$CONF"
+
+clear
+echo "PDSSHD v2.08 by:"
+echo "Geofferey@XDA forums"
+sleep 2
 
 clear
 
 PASSWORD (){
 echo "---ENTER-CURRENT-PASS---"
+if [ -z $PASS ]; then 
+echo ""
+echo "Please press ENTER to continue"; read return; clear
+else
 echo ""
 read -s -p "Enter password:" CPASS
 echo ""
+fi
 until [ "$CPASS" = "$PASS" ]; do
+echo ""
 read -s -p "Wrong password, try again:" CPASS
 echo ""
 done
@@ -29,7 +40,9 @@ mount -o remount,ro /system
 }
 
 SSHD_CONFIG (){
+if ! [ -z $PASS ]; then 
 echo ""
+fi
 echo "---CONFIGURE-SSH-DAEMON---"
 echo ""
 read -s -p "Enter new password:" NEWPASS
@@ -42,7 +55,7 @@ read -s -p "Enter new password:" NEWPASS;
 echo ""
 done
 
-sed -i -e"s/^PASS=.*/PASS=$NEWPASS/" /etc/sshd.conf
+sed -i -e"s/^PASS=.*/PASS=$NEWPASS/" "$CONF"
 if test $? -eq 0; then
 echo 'password written'
 else 
@@ -53,9 +66,9 @@ echo ""
 
 read -p "Enter new port: " NEWPORT
 if test "$NEWPORT" = ""; then
-echo "DEFAULT PORT #2222"; sed -i -e"s/^PORT=.*/PORT=2222/" /etc/sshd.conf 
+echo "DEFAULT PORT #2222"; sed -i -e"s/^PORT=.*/PORT=2222/" "$CONF"
 else
-sed -i -e"s/^PORT=.*/PORT=$NEWPORT/" /etc/sshd.conf 
+sed -i -e"s/^PORT=.*/PORT=$NEWPORT/" "$CONF"
 fi
 
 if test $? -eq 0; then
@@ -71,10 +84,10 @@ do
 read -r -p 'Enable SSH? ' choice
 case "$choice" in
 n|N|no|No|NO) echo "SSH disabled"; 
-sed -i -e"s/^SSH=.*/SSH=0/" /etc/sshd.conf 
+sed -i -e"s/^SSH=.*/SSH=0/" "$CONF"
 break;;
-y|Y|yes|Yes|YEs|YES|YeS|yeS|yES) echo "Reverse SSH enabled";
-sed -i -e"s/^SSH=.*/SSH=1/" /etc/sshd.conf 
+y|Y|yes|Yes|YEs|YES|YeS|yeS|yES) echo "SSH enabled";
+sed -i -e"s/^SSH=.*/SSH=1/" "$CONF"
 break;;
 *) echo 'Nothing done'; 
 break;;
@@ -88,10 +101,10 @@ do
 read -r -p 'Enable Wakelock on Connect? ' choice
 case "$choice" in
 n|N|no|No|NO) echo "Wakelock disabled"; 
-sed -i -e"s/^WAKELOCK=.*/WAKELOCK=0/" /etc/sshd.conf 
+sed -i -e"s/^WAKELOCK=.*/WAKELOCK=0/" "$CONF"
 break;;
 y|Y|yes|Yes|YEs|YES|YeS|yeS|yES) echo "Wakelock enabled";
-sed -i -e"s/^WAKELOCK=.*/WAKELOCK=1/" /etc/sshd.conf 
+sed -i -e"s/^WAKELOCK=.*/WAKELOCK=1/" "$CONF"
 break;;
 *) echo 'Nothing done'; 
 break;;
@@ -105,10 +118,10 @@ do
 read -r -p 'Enable Notification on Connect? ' choice
 case "$choice" in
 n|N|no|No|NO) echo "Notification disabled"; 
-sed -i -e"s/^NOTIFY=.*/NOTIFY=0/" /etc/sshd.conf 
+sed -i -e"s/^NOTIFY=.*/NOTIFY=0/" "$CONF"
 break;;
 y|Y|yes|Yes|YEs|YES|YeS|yeS|yES) echo "Notification enabled";
-sed -i -e"s/^NOTIFY=.*/NOTIFY=1/" /etc/sshd.conf 
+sed -i -e"s/^NOTIFY=.*/NOTIFY=1/" "$CONF"
 break;;
 *) echo 'Nothing done'; 
 break;;
@@ -125,9 +138,9 @@ echo ""
 
 read -p "Enter reverse listen port: " NEWREVPORT
 if test "$NEWREVPORT" = ""; then
-echo "DEFAULT IS BLANK"; sed -i -e"s/^REVPORT=.*/REVPORT=/" /etc/sshd.conf 
+echo "DEFAULT IS BLANK"; sed -i -e"s/^REVPORT=.*/REVPORT=/" "$CONF"
 else
-sed -i -e"s/^REVPORT=.*/REVPORT=$NEWREVPORT/" /etc/sshd.conf 
+sed -i -e"s/^REVPORT=.*/REVPORT=$NEWREVPORT/" "$CONF"
 fi
 
 if test $? -eq 0; then
@@ -140,9 +153,9 @@ echo ""
 
 read -p "Enter remote server: " NEWREMSERV
 if test "$NEWREMSERV" = ""; then
-echo "DEFAULT IS BLANK"; sed -i -e"s/^REMSERV=.*/REMSERV=/" /etc/sshd.conf 
+echo "DEFAULT IS BLANK"; sed -i -e"s/^REMSERV=.*/REMSERV=/" "$CONF"
 else
-sed -i -e"s/^REMSERV=.*/REMSERV=$NEWREMSERV/" /etc/sshd.conf 
+sed -i -e"s/^REMSERV=.*/REMSERV=$NEWREMSERV/" "$CONF"
 fi
 
 if test $? -eq 0; then
@@ -155,9 +168,9 @@ echo ""
 
 read -p "Enter remote serv port: " NEWREMSERVPORT
 if test "$NEWREMSERVPORT" = ""; then
-echo "DEFAULT IS 22"; sed -i -e"s/^REMSERVPORT=.*/REMSERVPORT=22/" /etc/sshd.conf 
+echo "DEFAULT IS 22"; sed -i -e"s/^REMSERVPORT=.*/REMSERVPORT=22/" "$CONF"
 else
-sed -i -e"s/^REMSERVPORT=.*/REMSERVPORT=$NEWREMSERVPORT/" /etc/sshd.conf 
+sed -i -e"s/^REMSERVPORT=.*/REMSERVPORT=$NEWREMSERVPORT/" "$CONF"
 fi
 
 if test $? -eq 0; then
@@ -170,9 +183,9 @@ echo ""
 
 read -p "Enter remote username: " NEWREMUSER
 if test "$NEWREMUSER" = ""; then
-echo "DEFAULT IS BLANK"; sed -i -e"s/^REMUSER=.*/REMUSER=/" /etc/sshd.conf 
+echo "DEFAULT IS BLANK"; sed -i -e"s/^REMUSER=.*/REMUSER=/" "$CONF"
 else
-sed -i -e"s/^REMUSER=.*/REMUSER=$NEWREMUSER/" /etc/sshd.conf 
+sed -i -e"s/^REMUSER=.*/REMUSER=$NEWREMUSER/" "$CONF"
 fi
 
 if test $? -eq 0; then
@@ -183,15 +196,21 @@ fi
 
 echo ""
 
+read -p "Enter path to remote private key: "  PRIKEYLOC
+echo ""
+echo "---CONVERTING-PRIVATE-KEY---"; mkdir /system/etc/.ssh; mkdir /sdcard/.ssh; rm /system/etc/.ssh/reverse_ssh_key; dropbearconvert openssh dropbear "$PRIKEYLOC" /system/etc/.ssh/reverse_ssh_key; chmod 400 /system/etc/.ssh/reverse_ssh_key; cp "$PRIKEYLOC" /system/etc/.ssh/openssh_key; chmod 400 /system/etc/.ssh/openssh_key
+
+echo ""
+
 while true 
 do
 read -r -p 'Enable Reverse SSH? ' choice
 case "$choice" in
 n|N|no|No|NO) echo "Reverse SSH disabled"; 
-sed -i -e"s/^REVSSH=.*/REVSSH=0/" /etc/sshd.conf 
+sed -i -e"s/^REVSSH=.*/REVSSH=0/" "$CONF"
 break;;
 y|Y|yes|Yes|YEs|YES|YeS|yeS|yES) echo "Reverse SSH enabled";
-sed -i -e"s/^REVSSH=.*/REVSSH=1/" /etc/sshd.conf 
+sed -i -e"s/^REVSSH=.*/REVSSH=1/" "$CONF"
 break;;
 *) echo 'Nothing done'; 
 break;;
@@ -207,9 +226,9 @@ echo ""
 
 read -p "Enter socks listen port: " NEWSOCKPORT
 if test "$NEWSOCKPORT" = ""; then
-echo "DEFAULT IS BLANK"; sed -i -e"s/^SOCKSPORT=.*/SOCKSPORT=/" /etc/sshd.conf 
+echo "DEFAULT IS BLANK"; sed -i -e"s/^SOCKSPORT=.*/SOCKSPORT=/" "$CONF"
 else
-sed -i -e"s/^SOCKSPORT=.*/SOCKSPORT=$NEWSOCKPORT/" /etc/sshd.conf 
+sed -i -e"s/^SOCKSPORT=.*/SOCKSPORT=$NEWSOCKPORT/" "$CONF"    
 fi
 
 if test $? -eq 0; then
@@ -225,10 +244,10 @@ do
 read -r -p 'Enable HTTP SSH? ' choice
 case "$choice" in
 n|N|no|No|NO) echo "HTTP SSH disabled"; 
-sed -i -e"s/^HTTPSSH=.*/HTTPSSH=0/" /etc/sshd.conf 
+sed -i -e"s/^HTTPSSH=.*/HTTPSSH=0/" "$CONF"
 break;;
 y|Y|yes|Yes|YEs|YES|YeS|yeS|yES) echo "HTTP SSH enabled";
-sed -i -e"s/^HTTPSSH=.*/HTTPSSH=1/" /etc/sshd.conf 
+sed -i -e"s/^HTTPSSH=.*/HTTPSSH=1/" "$CONF"
 break;;
 *) echo 'Nothing done'; 
 break;;
@@ -307,10 +326,10 @@ do
 read -r -p 'Enable DDNS? ' choice
 case "$choice" in
 n|N|no|No|NO) echo "DDNS disabled"; 
-sed -i -e"s/^INADYN=.*/INADYN=0/" /etc/sshd.conf 
+sed -i -e"s/^INADYN=.*/INADYN=0/" "$CONF"
 break;;
 y|Y|yes|Yes|YEs|YES|YeS|yeS|yES) echo "DDNS enabled";
-sed -i -e"s/^INADYN=.*/INADYN=1/" /etc/sshd.conf 
+sed -i -e"s/^INADYN=.*/INADYN=1/" "$CONF"
 break;;
 *) echo 'Nothing done'; 
 break;;
@@ -330,7 +349,7 @@ while true
     n|N|no|No|NO) echo "Keeping old key(s)";
     break;;
     y|Y|yes|Yes|YEs|YES|YeS|yeS|yES) echo "Removing old key(s)";
-    rm /etc/dropbear/data/br.com.bott.droidsshd/files/etc/dropbear_*_host_key;
+    rm /etc/dropbear/dropbear_*_host_key;
     break;;
     *) echo 'Keeping old key(s)'; 
     break;;
@@ -339,22 +358,37 @@ while true
 
 echo ""
 
-echo "---GENERATING-RSA-KEY---"; dropbearkey -t rsa -f /etc/dropbear/data/br.com.bott.droidsshd/files/etc/dropbear_rsa_host_key; chmod 400 /etc/dropbear/data/br.com.bott.droidsshd/files/etc/dropbear_rsa_host_key
+echo "---GENERATING-RSA-KEY---"; dropbearkey -t rsa -f /etc/dropbear/dropbear_rsa_host_key; chmod 400 /etc/dropbear/dropbear_rsa_host_key
 
 echo ""
 
-echo "---GENERATING-DSS-KEY---"; dropbearkey -t dss -f /etc/dropbear/data/br.com.bott.droidsshd/files/etc/dropbear_dss_host_key; chmod 400 /etc/dropbear/data/br.com.bott.droidsshd/files/etc/dropbear_dss_host_key 
+echo "---GENERATING-DSS-KEY---"; dropbearkey -t dss -f /etc/dropbear/dropbear_dss_host_key; chmod 400 /etc/dropbear/dropbear_dss_host_key 
 
 echo ""
 
-read -p "Enter path to private key: "  PRIKEYLOC
+echo "---GENERATING-PRI-RSA-KEY---"; dropbearkey -t rsa -f /sdcard/device-pri-key
+
 echo ""
-echo "---CONVERTING-PRIVATE-KEY---"; mkdir /system/etc/.ssh; mkdir /sdcard/.ssh; rm /system/etc/.ssh/reverse_ssh_key; dropbearconvert openssh dropbear "$PRIKEYLOC" /system/etc/.ssh/reverse_ssh_key; chmod 400 /system/etc/.ssh/reverse_ssh_key; cp "$PRIKEYLOC" /system/etc/.ssh/openssh_key; chmod 400 /system/etc/.ssh/openssh_key
+
+echo "---GENERATING-PUB-RSA-KEY---"; dropbearkey -y -f /sdcard/device-pri-key > /etc/.ssh/authorized_keys/id_rsa.pub; chmod 400 /etc/.ssh/authorized_keys/id_rsa.pub; 
+echo "---The DEVICE PRIVATE KEY located in:"
+echo "/sdcard/device-pri-key is now authorized for use"
+
+echo ""
+
+echo "---CONVERTING-RSA-KEY---"; dropbearconvert dropbear openssh /sdcard/device-pri-key /sdcard/device-pri-key-openssh
+
+echo ""
+
+echo "The private keys used to access this device are located on the sdcard."
+echo "Please move them to a safe location."
 }
 
 
 HELP () {
 echo "Available options:"
+echo " -a configures AIO"
+echo " -b config BACKUP"
 echo " -s configures SSH"
 echo " -r configures REVERSE SSH"
 echo " -p configures HTTP SOCKS PROXY"
@@ -393,7 +427,7 @@ echo ""; echo "Press RETURN to continue"; read return; clear
 
 EXECUTE (){
 if test $SSH -eq 1; then
-./system/exbin/dropbear -A -N root -U 0 -G 0 -C "$PASS" -p "$PORT"
+./system/exbin/dropbear -A -N root -U 0 -G 0 -R /etc/.ssh/authorized_keys/id_rsa.pub -C "$PASS" -p "$PORT"
 echo "Check if Dropbear is running..."
 echo ""
 ps | grep dropbear
@@ -446,9 +480,11 @@ OPENSSHKEY=/system/etc/.ssh/openssh_key
 UNINSTALL (){
 while true 
   do
-    read -r -p 'Remove old key(s)? ' CHOICE
+    echo ""
+    read -r -p 'Uninstall PDSSHD? ' CHOICE
     case "$CHOICE" in
-    n|N|no|No|NO) echo "Keeping old key(s)";
+    n|N|no|No|NO) echo "";
+                               echo "Aborting 'Uninstall!";
     break;;
     y|Y|yes|Yes|YEs|YES|YeS|yeS|yES) echo "Uninstalling PDSSHD....";
     sleep 1;
@@ -459,32 +495,21 @@ while true
     rm /system/xbin/ssh_auto;
     rm /system/xbin/reverse_ssh;
     rm /system/xbin/http_ssh;
-    rm /system/xbin/openssh;
     rm /system/xbin/inadyn;
     rm /system/xbin/rsync;
     rm /system/xbin/sshd_config;
     rm /system/etc/sshd.conf;
     rm /system/etc/inadyn.conf;
-    rm /system/lib/libssh.so;
-
-    if [[ -e /system/etc/init.d/80httptunnel ]]; then
-    rm /system/etc/init.d/80httptunnel
-    fi
-
-    if [[ -e /system/etc/init.d/70sshtunnel ]]; then
-    rm /system/etc/init.d/70sshtunnel
-    fi
 
     if [[ -e /system/etc/init.d/60dropbear ]]; then
     rm /system/etc/init.d/60dropbear
     fi
 
-    if [[ -e /system/etc/init.d/50inadyn ]]; then
-    rm /system/etc/init.d/50inadyn
+    if [[ -e /system/su.d/60dropbear ]]; then
+    rm /system/su.d/60dropbear
     fi
 
     rm /system/xbin/dropbearkey
-    rm /data/data/br.com.bott.droidsshd
 
     echo "";
 
@@ -555,24 +580,72 @@ echo ""
 fi
 }
 
+BACKUP () { 
+if ! [ -e /data/etc ]; then
+mkdir /data/etc
+chmod -R 0600 /data/etc
+else
+chmod -R 0600 /data/etc
+fi
+
+if [ -e /data/etc/dropbear ]; then 
+rm -r /data/etc/dropbear
+fi
+
+cp -R /etc/dropbear /data/etc/dropbear
+
+if [ -d /data/etc/dropbear/.ssh ]; then 
+rm -r /data/etc/dropbear/.ssh 
+fi
+
+cp -R /system/etc/.ssh /data/etc/
+
+if [ -e /data/etc/pdsshd.conf ]; then 
+rm /data/etc/pdsshd.conf
+fi
+
+cp /system/etc/pdsshd.conf /data/etc/pdsshd.conf
+
+if [ -e /data/etc/inadyn.conf ]; then 
+rm /data/etc/inadyn.conf
+fi
+
+cp /system/etc/inadyn.conf /data/etc/inadyn.conf
+
+echo ""
+echo "Configuration backed up to /data/etc"
+echo ""
+}
+
+CONFIGURED () {
+sed -i -e"s/^CONFIGURED=.*/CONFIGURED=1/" "$CONF"
+sleep 1
+}
+
+
 
 if [[ $@ ]]; then
-    while getopts "srpdkechu" OPTION; do
+    while getopts "absrpdkechu" OPTION; do
         case $OPTION in
+            a) 
+                PASSWORD; MOUNT; SSHD_CONFIG; REVERSE_SSH; HTTP_PROXY; DDNS; KEYS; CONFIGURED; BACKUP; RESTART; UNMOUNT;
+                ;;
+            b) PASSWORD; BACKUP 
+                ;;
             s)
-                PASSWORD; MOUNT; SSHD_CONFIG; UNMOUNT; RESTART
+                PASSWORD; MOUNT; SSHD_CONFIG; CONFIGURED; UNMOUNT; BACKUP; RESTART
                 ;;
             r)
-                PASSWORD; MOUNT; REVERSE_SSH; UNMOUNT
+                PASSWORD; MOUNT; REVERSE_SSH; CONFIGURED; UNMOUNT; BACKUP
                 ;;
             p)
-                PASSWORD; MOUNT; HTTP_PROXY; UNMOUNT
+                PASSWORD; MOUNT; HTTP_PROXY; CONFIGURED; UNMOUNT; BACKUP
                 ;;
             d) 
-                PASSWORD; MOUNT; DDNS; UNMOUNT
+                PASSWORD; MOUNT; DDNS; CONFIGURED; UNMOUNT; BACKUP
                 ;;
             k)
-                PASSWORD; MOUNT; KEYS; UNMOUNT; RESTART
+                PASSWORD; MOUNT; KEYS; CONFIGURED; UNMOUNT; RESTART; BACKUP
                 ;;
             e) 
                 EXECUTE
@@ -584,7 +657,7 @@ if [[ $@ ]]; then
                 HELP
                 ;;
             u) 
-                PASSWORD; MOUNT UNINSTALL; UNMOUNT
+                PASSWORD; MOUNT; UNINSTALL; UNMOUNT
                 ;;
             \?)
                 HELP
@@ -592,15 +665,7 @@ if [[ $@ ]]; then
         esac
     done
 else
-    PASSWORD;
-    MOUNT;
-    SSHD_CONFIG;
-    REVERSE_SSH;
-    HTTP_PROXY;
-    DDNS;
-    KEYS;
-    RESTART;
-    UNMOUNT
+    HELP
 fi
 
 sleep 1
